title: <span style="text-align:center;">vivienne prince</span> # website title
logo: "/images/logo.png?raw=true" # logo
description: > # your text below
  Thanks for dropping by my page! <br><br>
  I'm a Masters of Data Science student graduating in 2022.<br><br>
  I really enjoy learning new tools, exploring data to help solve problems, and helping others understand ideas and data.
  <br>


theme: jekyll-theme-minimal
google_analytics: G-ESQ433ZWGK # Google Analytics tracking ID
